version: '3.9'
services:
  url:
    image: ozon/url
    ports:
      - "8081:8081"
    environment:
      STORAGE_TYPE: ${STORAGE_TYPE}
    command: "/url"

  microservice-waiter:
    image: alpine
    depends_on:
      url:
        condition: service_started

  api:
    image: ozon/api
    ports:
      - "8082:8082"
    depends_on:
      microservice-waiter:
        condition: service_completed_successfully
    command: "/api"
