// Code generated by MockGen. DO NOT EDIT.
// Source: internal/url/usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	models "main/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CreateShortUrlAndSave mocks base method.
func (m *MockUseCase) CreateShortUrlAndSave(ctx context.Context, url models.Url) (models.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortUrlAndSave", ctx, url)
	ret0, _ := ret[0].(models.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortUrlAndSave indicates an expected call of CreateShortUrlAndSave.
func (mr *MockUseCaseMockRecorder) CreateShortUrlAndSave(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortUrlAndSave", reflect.TypeOf((*MockUseCase)(nil).CreateShortUrlAndSave), ctx, url)
}

// GetFullUrl mocks base method.
func (m *MockUseCase) GetFullUrl(ctx context.Context, url models.Url) (models.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullUrl", ctx, url)
	ret0, _ := ret[0].(models.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullUrl indicates an expected call of GetFullUrl.
func (mr *MockUseCaseMockRecorder) GetFullUrl(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullUrl", reflect.TypeOf((*MockUseCase)(nil).GetFullUrl), ctx, url)
}
