// Code generated by MockGen. DO NOT EDIT.
// Source: internal/url/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetFullUrl mocks base method.
func (m *MockRepository) GetFullUrl(ctx context.Context, short string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullUrl", ctx, short)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullUrl indicates an expected call of GetFullUrl.
func (mr *MockRepositoryMockRecorder) GetFullUrl(ctx, short interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullUrl", reflect.TypeOf((*MockRepository)(nil).GetFullUrl), ctx, short)
}

// SaveShortToFullUrl mocks base method.
func (m *MockRepository) SaveShortToFullUrl(ctx context.Context, short, full string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShortToFullUrl", ctx, short, full)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveShortToFullUrl indicates an expected call of SaveShortToFullUrl.
func (mr *MockRepositoryMockRecorder) SaveShortToFullUrl(ctx, short, full interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShortToFullUrl", reflect.TypeOf((*MockRepository)(nil).SaveShortToFullUrl), ctx, short, full)
}
